import { OnInit, OnChanges, SimpleChanges, ElementRef, EventEmitter } from '@angular/core';
import { DropzoneConfig, DropzoneConfigInterface } from './dropzone.interfaces';
export declare class DropzoneComponent implements OnInit, OnChanges {
    private elementRef;
    private defaults;
    private dropzone;
    private dropzoneConfig;
    private dropzoneElement;
    config: DropzoneConfigInterface;
    placeholder: string;
    uploadDone: EventEmitter<any>;
    uploadError: EventEmitter<Object>;
    logging: boolean;
    sending: Function;
    removedFile: Function;
    addedFile: Function;
    accept: Function;
    complete: Function;
    dragenter: Function;
    dragend: Function;
    drop: Function;
    showOriginalContainer: boolean;
    queuecomplete: Function;
    constructor(elementRef: ElementRef, defaults: DropzoneConfig);
    ngOnInit(): void;
    getDropzoneInstances(): any;
    private defaultCallback(e);
    processFile(url: any, file: any): void;
    getDropzone(): any;
    ngOnChanges(changes: SimpleChanges): void;
}
